[package]
name = "proyecto-final-sd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
actix-cors = "0.6.4"
serde = { version = "1.0.152", features = ["derive"] }
sqlx ={ version = "0.7.2" ,features = ["sqlite", "runtime-tokio-rustls"] }
sha3 = "0.10.8"
